# Generated by Django 5.0.1 on 2024-02-02 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('type', models.CharField(default='none', max_length=50)),
                ('num_per_node', models.IntegerField(default=0)),
                ('num_cpus_per_node', models.IntegerField(default=0)),
                ('main_mem_per_node', models.IntegerField(default=0)),
                ('node_name', models.CharField(default='local', max_length=255, unique=True)),
                ('node_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255, unique=True)),
                ('type', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Base', max_length=255, unique=True)),
                ('type', models.CharField(default='carme', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('information', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=False)),
                ('owner', models.CharField(default='admin', max_length=50)),
                ('bind', models.CharField(default='none', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHasFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.flag')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.image')),
            ],
            options={
                'unique_together': {('image', 'flag')},
            },
        ),
        migrations.AddField(
            model_name='flag',
            name='flag',
            field=models.ManyToManyField(through='projects.ImageHasFlag', to='projects.image'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('num', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='none', max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('information', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_expired', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHasTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('sent', 'sent'), ('accepted', 'accepted')], default='none', max_length=8)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_approved_by_manager', models.BooleanField(default=False)),
                ('is_approved_by_admin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResourceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(default='none', max_length=255)),
                ('maxjobs', models.IntegerField(default=4)),
                ('maxnodes_per_job', models.IntegerField(default=1)),
                ('maxaccels_per_node', models.IntegerField(default=1)),
                ('walltime', models.IntegerField(default=3)),
                ('partition', models.CharField(max_length=255)),
                ('features', models.TextField(blank=True, default='')),
                ('template', models.ManyToManyField(through='projects.ProjectHasTemplate', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='projecthastemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.resourcetemplate'),
        ),
        migrations.CreateModel(
            name='TemplateHasAccelerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accelerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.accelerator')),
                ('resourcetemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.resourcetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='accelerator',
            name='accelerator',
            field=models.ManyToManyField(through='projects.TemplateHasAccelerator', to='projects.resourcetemplate'),
        ),
        migrations.CreateModel(
            name='TemplateHasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.image')),
                ('resourcetemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.resourcetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ManyToManyField(through='projects.TemplateHasImage', to='projects.resourcetemplate'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_project_name'),
        ),
        migrations.AlterUniqueTogether(
            name='projecthastemplate',
            unique_together={('project', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='templatehasaccelerator',
            unique_together={('resourcetemplate', 'accelerator')},
        ),
        migrations.AlterUniqueTogether(
            name='templatehasimage',
            unique_together={('resourcetemplate', 'image')},
        ),
    ]
