# Generated by Django 4.1.6 on 2023-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_accelerator_projecthastemplate_resourcetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='is_accepted_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
