# Generated by Django 4.1.6 on 2023-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_department_project_is_accepted_by_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_accepted_by_user',
            new_name='checked',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_number',
            new_name='num',
        ),
        migrations.AddField(
            model_name='project',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
