# Generated by Django 4.1.7 on 2023-03-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_is_accepted_by_user_project_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='classification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='num',
            field=models.CharField(max_length=255),
        ),
    ]
