# Generated by Django 3.2.23 on 2023-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20231127_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetemplate',
            name='maxaccels_per_node',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resourcetemplate',
            name='maxnodes_per_job',
            field=models.IntegerField(default=1),
        ),
    ]
