# Generated by Django 3.2.23 on 2023-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20231204_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bind',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
