# Generated by Django 3.2.23 on 2023-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_image_bind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bind',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
