# traefik.toml
[log]
  level = "INFO"
  filePath = "/var/log/traefik/traefik.log"

[providers]
  providersThrottleDuration = "2s"
  [providers.file]
    directory = "/opt/traefik/routes"
    watch = true

[api]
  insecure = true
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":10080"
  [entryPoints.dashboard]
    address = ":8081"
  [entryPoints.https]
    address = ":10443"

[serversTransport]
  insecureSkipVerify = true
