#!python

import sys
from os import access, R_OK
from os.path import isfile
from carme_backend import VERSION
from carme_backend.server import start

# Include standard modules
import argparse

# Initiate the parser
parser = argparse.ArgumentParser(description='Backend server for the high performance computing ai suite Carme.')

parser.add_argument('config', type=str,
                    help='path to carme configuration file')
#parser.add_argument('-p --port', type=int, dest='port', default=56789,
#                    help='listened port')
#parser.add_argument('-k --key', type=str, dest='key',
#                    help='path to key file')
#parser.add_argument('-c --cert', type=str, dest='cert',
#                    help='path to cert file')
parser.add_argument('-V --version', action='version', version=f'%(prog)s v{VERSION}')

# Read arguments from the command line
args = parser.parse_args()

if not isfile(args.config) or not access(args.config, R_OK):
    raise Exception("Carme configuration file doesn't exist or is not readable.")

start(args)
