# Generated by Django 2.0.4 on 2019-01-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0003_carmemesaages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarmeMesaages',
            new_name='CarmeMessages',
        ),
    ]
