# Generated by Django 2.0.4 on 2019-01-28 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0004_auto_20190118_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('free', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('queued', models.IntegerField(default=0)),
            ],
        ),
    ]
