# Generated by Django 2.0.4 on 2019-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme-base', '0006_slurmjobs_frontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
                ('group_partition', models.CharField(max_length=128)),
                ('group_default', models.BooleanField()),
                ('group_max_jobs', models.IntegerField()),
                ('group_max_nodes', models.IntegerField()),
                ('group_max_gpus_per_node', models.IntegerField()),
            ],
        ),
    ]
