# Generated by Django 2.2.3 on 2019-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme-base', '0007_groupresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurmjobs',
            name='gpu_type',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='runingjobs',
            name='status',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
