# Generated by Django 2.2.3 on 2019-10-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carme-base', '0008_auto_20191010_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuningJobs',
        ),
    ]
