# Generated by Django 2.2.3 on 2020-04-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme-base', '0012_slurmjobs_add_ta_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slurmjobs',
            name='gpu_ids',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='ip',
            field=models.CharField(default='1.1.1.1', max_length=512),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='nb_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='slurm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='ta_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='tb_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slurmjobs',
            name='url_suffix',
            field=models.CharField(default='unknown', max_length=512),
        ),
    ]
