# Generated by Django 5.0.1 on 2024-02-02 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarmeJobTable',
            fields=[
                ('job_db_inx', models.BigAutoField(primary_key=True, serialize=False)),
                ('mod_time', models.BigIntegerField()),
                ('deleted', models.IntegerField()),
                ('account', models.TextField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('array_task_str', models.TextField(blank=True, null=True)),
                ('array_max_tasks', models.PositiveIntegerField()),
                ('array_task_pending', models.PositiveIntegerField()),
                ('cpus_req', models.PositiveIntegerField()),
                ('derived_ec', models.PositiveIntegerField()),
                ('derived_es', models.TextField(blank=True, null=True)),
                ('exit_code', models.PositiveIntegerField()),
                ('job_name', models.TextField()),
                ('id_assoc', models.PositiveIntegerField()),
                ('id_array_job', models.PositiveIntegerField()),
                ('id_array_task', models.PositiveIntegerField()),
                ('id_block', models.TextField(blank=True, null=True)),
                ('id_job', models.PositiveIntegerField()),
                ('id_qos', models.PositiveIntegerField()),
                ('id_resv', models.PositiveIntegerField()),
                ('id_wckey', models.PositiveIntegerField()),
                ('id_user', models.PositiveIntegerField()),
                ('id_group', models.PositiveIntegerField()),
                ('kill_requid', models.IntegerField()),
                ('mem_req', models.BigIntegerField()),
                ('nodelist', models.TextField(blank=True, null=True)),
                ('nodes_alloc', models.PositiveIntegerField()),
                ('node_inx', models.TextField(blank=True, null=True)),
                ('partition', models.TextField()),
                ('priority', models.PositiveIntegerField()),
                ('state', models.PositiveIntegerField()),
                ('timelimit', models.PositiveIntegerField()),
                ('time_submit', models.BigIntegerField()),
                ('time_eligible', models.BigIntegerField()),
                ('time_start', models.BigIntegerField()),
                ('time_end', models.BigIntegerField()),
                ('time_suspended', models.BigIntegerField()),
                ('gres_req', models.TextField()),
                ('gres_alloc', models.TextField()),
                ('gres_used', models.TextField()),
                ('wckey', models.TextField()),
                ('track_steps', models.IntegerField()),
                ('tres_alloc', models.TextField()),
                ('tres_req', models.TextField()),
            ],
            options={
                'db_table': 'mycluster_job_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarmeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('message', models.CharField(default='message', max_length=512)),
                ('color', models.CharField(default='gray', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('free', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('queued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_custom_message', models.BooleanField(default=False)),
                ('custom_message', models.TextField(blank=True, default='Type your message')),
                ('carme_message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SlurmJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('num_nodes', models.IntegerField(default=1)),
                ('num_gpus', models.IntegerField(default=1)),
                ('slurm_id', models.IntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=64)),
                ('ip', models.CharField(default='1.1.1.1', max_length=512)),
                ('url_suffix', models.CharField(default='unknown', max_length=512)),
                ('nb_port', models.IntegerField(default=0)),
                ('tb_port', models.IntegerField(default=0)),
                ('ta_port', models.IntegerField(default=0)),
                ('gpu_ids', models.CharField(default='none', max_length=64)),
                ('image_name', models.CharField(default='no image', max_length=128)),
                ('name', models.CharField(default='unknown', max_length=128)),
                ('frontend', models.CharField(default='main', max_length=64)),
                ('gpu_type', models.CharField(default='none', max_length=64)),
            ],
        ),
    ]
