# Generated by Django 4.2.4 on 2023-08-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_custom_message', models.BooleanField(default=False)),
                ('custom_message', models.TextField(blank=True, default='Type your message')),
                ('carme_message', models.TextField(blank=True, default='')),
            ],
        ),
    ]
