# Generated by Django 3.2.23 on 2023-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0002_newsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurmjob',
            name='node_name',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
