# Generated by Django 3.2.23 on 2023-12-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0003_slurmjob_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurmjob',
            name='node_name',
        ),
    ]
