# Generated by Django 2.0.4 on 2019-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carme', '0005_clusterstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurmjobs',
            name='frontend',
            field=models.CharField(default='main', max_length=64),
        ),
    ]
